# Generated by Django 4.0.5 on 2022-07-29 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('handbook', '0003_alter_publisher_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Book's name")),
                ('foto', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('number_of_pages', models.IntegerField(blank=True, null=True, verbose_name='Pages')),
                ('cover', models.CharField(blank=True, max_length=15, null=True, verbose_name='Cover')),
                ('bookformat', models.CharField(blank=True, max_length=20, null=True, verbose_name='Bookformat')),
                ('isbn', models.CharField(blank=True, max_length=25, null=True, verbose_name='ISBN')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Weight')),
                ('restrictions', models.IntegerField(blank=True, null=True, verbose_name='Restrictions')),
                ('number_of_books', models.IntegerField(blank=True, null=True, verbose_name='Number of books')),
                ('activity', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=20, verbose_name='Active y/n')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Rating')),
                ('date_of_creation', models.DateField(auto_now_add=True, verbose_name='Date of creation')),
                ('date_of_edit', models.DateField(auto_now=True, verbose_name='Date of edit')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authors', to='handbook.author', verbose_name='Author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genres', to='handbook.bookgenre', verbose_name='Genre')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publishers', to='handbook.publisher', verbose_name='Publisher')),
                ('seria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='handbook.bookseries', verbose_name='Seria')),
            ],
        ),
    ]
