# Generated by Django 4.0.5 on 2022-07-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Publisher')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='surname',
            field=models.CharField(default='alexander', max_length=25, verbose_name="Author's surname"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Authors name'),
        ),
        migrations.AlterField(
            model_name='bookgenre',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Bookgenre'),
        ),
        migrations.AlterField(
            model_name='bookseries',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Bookseries'),
        ),
    ]
