# Generated by Django 4.0.5 on 2022-07-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0002_publisher_author_surname_alter_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Publisher'),
        ),
    ]
