# Generated by Django 4.0.5 on 2022-08-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adress',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Adress'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Phone number'),
        ),
    ]
